waku-org/waku-go-bindings

- waku/nwaku.go
- waku/nwaku_test.go
Adding all configurations related to the setup of Lightpush, Filter and Store protocols.
In addition, changed the name of the `EnableRelay` and `NodeKey` fields in `WakuConfig` for `Relay` and `Nodekey` respectively.
That was done for consistency, so all the fields in `WakuConfig` match 1 to 1 to the names in https://github.com/waku-org/nwaku/blob/master/waku/factory/external_config.nim with the only difference that in `WakuConfig` the first letter of each field name is capitalized.
> chore: adding configurations for lightpush, filter and store

- waku/nwaku.go
- waku/nwaku_test.go
Adding Relay test, re-ordering the ports used in `nwaku_test.go` and adding a `(w *Waku) RelayPublish` function
The new tests passes using nwaku at the https://github.com/waku-org/nwaku/tree/chore-configure-external-callbacks branch, which includes a fix in which libwaku automatically subscribes to all the shards provided in the node's config
> chore: adding relay test

- waku/nwaku.go
- waku/nwaku_test.go
Following the discussion in https://github.com/waku-org/waku-go-bindings/pull/8#discussion_r1884148510 , adding a `ctx` parameter in `func (w *Waku) DialPeer` and `func (w *Waku) DialPeerByID`
> chore: pass ctx in dial functions

- waku/nwaku.go
- waku/nwaku_test.go
Cleaning up unnecessary parts that were inherited from status-go, mainly:
- The `Waku` type
- Usage of `ctx` and `cancel`
- Unnecessary goroutine
> chore: code cleanup

- waku/nwaku.go
- waku/nwaku_test.go
Integrating the connection change event and adding a test for it.
This requires the following nwaku PR to be merged: https://github.com/waku-org/nwaku/pull/3225
> feat: integrating connection change event

- waku/nwaku.go
Removing negentropy dependency now that it's not part of nwaku
> chore: remove negentropy dependency

- README.md
- waku/Makefile
Moving the Makefile to the `waku` package so it is copied when adding the dependency with `go get`
> chore: improve package structure

- waku/common/envelope.go
- waku/common/message_hash.go
- waku/common/store.go
- waku/nwaku.go
- waku/nwaku_test.go
Adapting the codebase to the usage of message hashes as hex strings in Relay and Store.
Included a new `MessageHash` type which is used whenever the bindings interact with message hashes, and added a test for Store.
A PR in nwaku returning message hashes in hex was also opened: https://github.com/waku-org/nwaku/pull/3234
> chore: using msg hash in hex and adding store test

- waku/nwaku.go
- waku/nwaku_test.go
Moving [GetFreePortIfNeeded](https://github.com/status-im/status-go/blob/feature/nwaku-in-status/wakuv2/nwaku.go#L3343-L3389) to the repo and using it in the tests.
Making the function public so it can be then removed from `status-go` too
> chore: automatically choosing ports

- waku/nwaku.go
Fix missing use of waitgroup in `GetNumConnectedRelayPeers`
> fix: properly using waitgroup in GetNumConnectedRelayPeers

- waku/nwaku.go
When having `omitempty` configured for Relay, whenever we set it to false it is considered as empty and the configuration is not sent to the nwaku node. As the default in `nwaku` is having Relay enabled, we end up having Relay enabled even if the user configured it false.
Therefore, removing the `omitempty` so we actually send the configuration when we disable it.
> fix: turning off omitempty for Relay

- waku/Makefile
Whenever `waku-go-bindings` is used as a dependency, nwaku must be cloned as `waku-go-bindings` references libwaku's header file.
In this PR I'm cloning nwaku and building libwaku in different targets, so it saves time whenever we don't use nwaku but still need the header file to compile the vendor. By doing this we avoid an unnecessary lengthy build
> chore: adding makefile targets

- waku/common/config.go
- waku/common/rate_limit.go
- waku/nwaku.go
- waku/nwaku_test.go
- waku/test_data.go
Moving types that will be needed by `status-go` without nwaku to the `common` package.
This will allow proper compilation of the dependency even when nwaku is not used, and it will spare us from having to clone nwaku at all if it's not needed.
> chore: moving types to common package

- waku/nwaku.go
Avoid exiting the program when a call to libwaku fails. The caller checks and handles the return value accordingly.
> fix: not exiting the program when a call fails

- waku/nwaku.go
Whenever we destroy a node we should delete it from our node registry. Otherwise, the same pointer may be used by a new node and the already destroyed `WakuNode`'s struct will be mistakenly taken from the registry on events instead of the newer node.
> fix: unregistering node when destroying

- README.md
Adding a link to the `example-go-bindings` repo for users to use as a reference if needed
> chore: adding link to example-go-bindings repo in readme

- waku/nwaku.go
- waku/peer_connections_test.go
Integrating libwaku's `waku_relay_get_peers_in_mesh` function introduced in https://github.com/waku-org/nwaku/pull/3352 and adding test (same test as for `waku_relay_get_num_peers_in_mesh` but checking the peerIds)
> feat: integrating waku_relay_get_peers_in_mesh

- waku/nwaku.go
- waku/relay_test.go
- waku/test_data.go
Integrating libwaku's `waku_relay_get_connected_peers` function introduced in https://github.com/waku-org/nwaku/pull/3353 and adding test
> feat: integrating waku_relay_get_connected_peers

- waku/common/peers.go
- waku/nwaku.go
- waku/peer_connections_test.go
Integrating libwaku's `waku_get_connected_peers_info` function introduced in https://github.com/waku-org/nwaku/pull/3356
[#3076 ](https://github.com/waku-org/nwaku/issues/3076)
> feat: integrating libwaku's waku_get_connected_peers_info

- waku/common/envelope.go
- waku/nwaku.go
- waku/nwaku_test_utils.go
Defining an Envelope type as in https://github.com/waku-org/go-waku/blob/master/waku/v2/protocol/envelope.go so it can be used directly in `status-go`
> chore: using envelope type instead of interface

- waku/nwaku.go
If any channel is full, we drop the event instead of blocking the entire node.
Issue: https://github.com/waku-org/nwaku/issues/3182
> fix: avoid blocking nodes when channels are full

- waku/common/store.go
Using camelCase in json representation of the store query, after https://github.com/waku-org/nwaku/pull/3366
> fix: using camelCase in the store query json

- waku/common/config.go
Exposing the following nwaku configurations:
- `dnsDiscoveryNameServers`
- `dnsAddrsNameServers`
- `discv5EnrAutoUpdate`
- `maxConnections`
> chore: exposing additional nwaku configurations

- waku/nwaku.go
Following https://github.com/waku-org/sds-go-bindings/pull/4, adding the `waku` prefix to exported C types and functions
> chore: adding prefix to exported C types and functions

- .github/workflows/CI.yml
This pull-request tightens our GitHub Actions workflow:
Repeat tests ten times
We pass -count=10 to go test, so each test function executes ten consecutive times. Flaky behaviour surfaces quickly.
Stop the job as soon as something fails
The step now begins with set -euo pipefail. If go test returns a non-zero exit code, the pipeline exits immediately and the job turns red instead of masking the failure behind tee.
> Adjust count of each test runs to 15

- waku/common/config.go
Removing `DnsDiscoveryNameServers` from the configurations as it was removed in https://github.com/waku-org/nwaku/commit/e42e28cc6f5f464d1efa65f8ed0b8ae58923f0de#diff-43f34e84eeb9a4b4061898c3bd78274e149e50bd6b5d24aeb0a982e07629172e
> chore: removing deprecated DnsDiscoveryNameServers config

- .gitignore
- README.md
- waku/Makefile
- waku/nwaku.go
The main reason:
We want to [stop vendoring](https://github.com/status-im/status-go/pull/6951) in status-go. This means that `waku-go-bindings` will be located in go cache, e.g.:
```
/Users/sirotin/go/pkg/mod/github.com/waku-org/waku-go-bindings@v0.0.0-20250925081015-f78f4286cb37
```
And the current solution (manually cloning `nwaku`) requires the user to call `sudo mkdir thirdparty`, which is:
1. requires user interaction, so can't automate the whole process
2. a bit unfriendly, because we're asking for `sudo`
For a `vendor/.../third_party/nwaku`, we were able to avoid `sudo` (or only do it once).
But in the new case each developer would need to do it manually.
I looked into some projects that are Go-wrappers for C++ libraries.
- For small libraries like …
> chore: use externally provided nwaku
